# Generated by Django 5.0.4 on 2024-05-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postmodel_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
